# Generated by Django 5.0 on 2023-12-12 11:57

import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfile",
            name="file",
            field=models.FileField(upload_to=mainapp.models.user_directory_path),
        ),
    ]
